export enum ActionType {
  AUTH_USER = 'AUTH_USER',

  GET_USERS = 'GET_USERS',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  IS_ERROR = 'IS_ERROR',
  IS_LOADING = 'IS_LOADING',

  ERROR = 'ERROR',
  ERROR_CLEAR = 'ERROR_CLEAR'
}
